# nginx-role.yml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: nginx-role
rules:
- apiGroups: [""]           # Empty string indicates the core API group (for Pods, Services, etc.)
  resources: ["pods"]
  verbs: ["get", "watch", "list", "create"]

